apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-224612-0c95-service
spec:
  selector:
    app: enterprise-system-224612-0c95
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
